Repository djeedai/bevy_tweening, pull requests merged in 2022-04, with the labels that each got.

#13 Fix `lib.rs` doc to not rely on feature
  src/lib.rs
Labels: documentation

#14 Upgrade `bevy-inspector-egui` and fix examples
  Cargo.toml
  examples/colormaterial_color.rs
  examples/menu.rs
  examples/sequence.rs
  examples/sprite_color.rs
  examples/text_color.rs
  examples/transform_rotation.rs
  examples/transform_translation.rs
  examples/ui_position.rs
Labels: examples

#11 Updated all document links to point to bevy 0.7.
  src/lens.rs
  src/lib.rs
  src/plugin.rs
Labels: documentation

#15 Add `Tween::set_direction()` for backward playback
  CHANGELOG.md
  src/lib.rs
  src/tweenable.rs
Labels: enhancement
