Repository djeedai/bevy_tweening, pull requests merged in 2022-10, with the labels that each got.

#63 Fix animator speed feature
  CHANGELOG.md
  src/lib.rs
  src/plugin.rs
Labels: bug

#65 Add more tests
  src/lens.rs
  src/lib.rs
  src/tweenable.rs
Labels: testing

#59 add an example to show menu hover animation
  examples/menu.rs
Labels: examples

#66 Add `assert_approx_eq!()` testing macro
  examples/menu.rs
  src/lib.rs
  src/test_utils.rs
  src/tweenable.rs
Labels: testing

#67 Add elapsed API
  CHANGELOG.md
  src/tweenable.rs
Labels: enhancement
