Repository djeedai/bevy_tweening, pull requests merged in 2023-10, with the labels that each got.

#104 Clarify doc around systems
  README.md
  src/lib.rs
  src/plugin.rs
Labels: documentation

#97 BackgroundColor support
  CHANGELOG.md
  README.md
  src/lens.rs
  src/plugin.rs
Labels: enhancement

#89 Fixed a panic in text color lens
  CHANGELOG.md
  src/lens.rs
Labels: bug

#107 Asset animator uses `Handle<T>` on same entity
  CHANGELOG.md
  examples/colormaterial_color.rs
  src/lens.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement, design
